#!/bin/bash
echo  更新库
apt-get update && apt-get upgrade && apt-get dist-upgrade
echo  删除旧版
rm -rf /usr/share/sqlmap >/dev/null 2>&1
rm -f /usr/bin/sqlmap >/dev/null 2>&1
rm -f /usr/bin/sqlmapapi >/dev/null 2>&1
killall sqlmap >/dev/null 2>&1
echo  更新python
apt-get install python -y >/dev/null 2>&1
echo 下载sqlmap
cd /usr/share >/dev/null 2>&1
git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap >/dev/null 2>&1
echo  下载完成更新环境变量
python -m compileall /usr/share/sqlmap/ >/dev/null 2>&1

echo /usr/share/sqlmap/sqlmap.py > /usr/bin/sqlmap
echo /usr/share/sqlmap/sqlmapapi.py > /usr/bin/sqlmapapi

chmod 7777 /usr/bin/sqlmap
chmod 7777 /usr/bin/sqlmapapi
chmod 777 /usr/share/sqlmap/sqlmap.py


#cd /usr/share/sqlmap >/dev/null 2>&1
#export PWD=/usr/share/sqlmap >/dev/null 2>&1
#source /etc/profile >/dev/null 2>&1
echo   安装sqlmap成功
echo
echo   启动sqlmap
sqlmap

rm -f sqlmap

